/**
 * Printable-parts tables for the build galleries (src/components/PartsGallery.astro).
 *
 * One entry per card. `base` is the filename stem the published renders and GLBs use
 * (`<base>_iso.png`, `<base>.glb`) — it must match the build repo's part name, because
 * both artefacts are generated by that repo's `build.py`. Bought parts have no render,
 * so their `base` is unused and they get a placeholder card.
 *
 * Print metadata is EDITORIAL — it comes from the build's design spec and log, not from
 * the CAD. Keep it in step with the repo when a part changes.
 */

export interface BuildPart {
  group: string;
  base: string;
  label: string;
  qty: string;
  material: string;
  orient: string;
  supports: string;
  note: string;
  bought?: boolean;
}

export interface BuildPartsTable {
  parts: BuildPart[];
  groupOrder: string[];
  groupNotes?: Record<string, string>;
}

/* ------------------------------------------------------------------ Daily Driver */

export const DAILY_DRIVER_PARTS: BuildPartsTable = {
  groupOrder: ['Earcup', 'Gimbal', 'Headband', 'Optional'],
  groupNotes: {
    Gimbal:
      'Plus the bought hardware per pivot (M3 shoulder screws + brass heat-set inserts). See the bill of materials.',
  },
  parts: [
    // --- Earcup (one piece) ---
    { group: 'Earcup', base: 'cup', label: 'Cup', qty: '×2', material: 'PETG',
      orient: 'Grille face down', supports: 'Light (pivot bosses)', note: 'One-piece earcup: triangular-lattice grille with the flush logo, buttressed baffle bosses, the yoke pivot bosses, and the earpad retaining lip. Damping is accessed from the front (baffle off).' },
    { group: 'Earcup', base: 'baffle', label: 'Baffle', qty: '×2', material: 'PETG / PLA+',
      orient: 'Flat', supports: 'No', note: 'Front driver-mount plate: driver guard + recess, 4 M3 rim holes, vents, and 3 standoffs for the clamp ring. The guard prints over the aperture.' },
    { group: 'Earcup', base: 'driver_clamp', label: 'Driver clamp ring', qty: '×2', material: 'PETG',
      orient: 'Recess up', supports: 'No', note: 'Retains the driver from the back: the driver’s rear nests into the ring’s recess, the inner shoulder catches the frame rim, and 3 M3 screws into baffle-back standoffs pull it tight.' },
    { group: 'Earcup', base: 'driver', label: 'Dynamic driver', qty: '×2', bought: true, material: '40 mm dynamic driver, 32 Ω',
      orient: '—', supports: '—', note: 'NOT printed: the bought driver. A mockup is shown in the 3D assembly above so the driver ↔ baffle ↔ clamp fit reads.' },
    // --- Gimbal ---
    { group: 'Gimbal', base: 'yoke', label: 'Fork-yoke', qty: '×2 (L/R mirror)', material: 'PETG',
      orient: 'Flat in its plane', supports: 'Minimal', note: 'Wraparound bracket. M3 shoulder-screw pivot, ±20° tilt with a hard stop. Mirror for left/right.' },
    // --- Headband ---
    { group: 'Headband', base: 'slider', label: 'Slider', qty: '×2', material: 'PETG',
      orient: 'Post bore vertical', supports: 'Light', note: 'Rounded Beyer-end-cap lozenge that clamps the 33 mm metal band: its two prongs drop into a recess and a cover plate + 2× M3 screws sandwich them. A slim post-bore barrel rides outside the band; the yoke’s round post slides in it for height and lets the cup swivel when unlocked, friction-locked by an M3 thumbscrew (Grado HP1000-style). Symmetric — the same print serves both ears.' },
    { group: 'Headband', base: 'headband_pad', label: 'Headband pad', qty: '×1', material: 'Foam or printed TPU',
      orient: 'Arch on its side', supports: 'Light', note: 'Rough-draft crown cushion; the channel grips the bow. Form/retention TBD.' },
    { group: 'Headband', base: 'bow', label: 'Head bow', qty: '×1', bought: true, material: 'Beyerdynamic Metal Head Bow (~$11) or DIY 1095 spring steel',
      orient: '—', supports: '—', note: 'NOT printed: the sprung headband is a bought/formed metal part (reference only).' },
    // --- Optional ---
    { group: 'Optional', base: 'grille_dot', label: 'Logo accent cap', qty: 'optional', material: 'Accent filament',
      orient: 'Any', supports: 'No', note: 'Optional press-in cap at the grille centre. The logo is flush single-colour by default — add this only if you want a contrasting accent.' },
    { group: 'Optional', base: 'adapter_ring', label: 'Driver adapter ring', qty: 'optional', material: 'PETG',
      orient: 'Flat', supports: 'No', note: 'Step-down ring to host a smaller driver in a larger baffle. NOT acoustically neutral.' },
  ],
};

/* -------------------------------------------------------------------- First Chair */

export const FIRST_CHAIR_PARTS: BuildPartsTable = {
  groupOrder: ['Earcup', 'Gimbal', 'Headband', 'Earpads', 'Optional'],
  groupNotes: {
    Gimbal:
      'Plus the bought hardware per pivot (M3 shoulder screws + brass heat-set inserts). See the bill of materials.',
    Earpads:
      'First Chair ships no pad and designs none. The cup rim is built to the Grado pattern so the whole aftermarket fits — that is the one interface where we deliberately do not innovate, because diverging costs you every pad you could otherwise buy.',
  },
  parts: [
    // --- Earcup ---
    { group: 'Earcup', base: 'cup', label: 'Cup', qty: '×2', material: 'PETG',
      orient: 'Grille face down', supports: 'Light (pivot bosses)', note: 'One-piece Ø48 shell with a Ø54 front lip overhanging it — that step is what holds the pad on. Rear triangular-lattice grille with the logo riding flush on it, four buttressed baffle bosses embedded in the wall, and the two yoke pivot bosses. Damping goes in from the front, baffle off.' },
    { group: 'Earcup', base: 'baffle', label: 'Baffle', qty: '×2', material: 'PETG / PLA+',
      orient: 'Flat', supports: 'No', note: 'Separate front plate carrying the driver — deliberately separate so it is the part you iterate on. Aperture, printed guard, driver seat + locating collar, controlled vents, and 4 M3 holes into the cup bosses. Still on Daily Driver’s plate diameter; a rebuild at Ø54 is the next job.' },
    { group: 'Earcup', base: 'driver_clamp', label: 'Driver clamp ring', qty: '×2', material: 'PETG',
      orient: 'Recess up', supports: 'No', note: 'Holds the driver against the baffle back with 3 M3 screws — no adhesive, so the driver comes out again. Chosen for serviceability over manufacturability, which is this build’s standing tie-breaker: the user is a tweaker.' },
    { group: 'Earcup', base: 'driver', label: 'Dynamic driver', qty: '×2', bought: true, material: '40 mm dynamic driver, ~32 Ω',
      orient: '—', supports: '—', note: 'NOT printed. 40 mm is the standard and the design does not chase a non-standard part. A mockup appears in the 3D assembly so the driver ↔ baffle ↔ clamp fit reads.' },
    // --- Gimbal ---
    { group: 'Gimbal', base: 'yoke', label: 'Fork-yoke', qty: '×2 (L/R mirror)', material: 'PETG',
      orient: 'Flat in its plane, layers along the arm', supports: 'Minimal', note: 'Fork from slider to cup, carrying the tilt axis on an M3 shoulder screw. Print orientation is not a suggestion here: the arms carry bending load and layer adhesion is the weak axis, so the layer lines must run ALONG the arm. This is the difference between a yoke that lasts and one that snaps.' },
    // --- Headband ---
    { group: 'Headband', base: 'slider', label: 'Slider', qty: '×2', material: 'PETG',
      orient: 'Post bore vertical', supports: 'Light', note: 'Screws to the bow’s end tabs and carries height adjustment plus the yoke swivel. Screws are spent here on purpose — it is the one joint carrying sustained spring load, and using the tabs the bow already has retires it as a research problem.' },
    { group: 'Headband', base: 'slider_shoe', label: 'Pressure shoe', qty: '×2', material: 'PETG or Delrin',
      orient: 'Saddle up', supports: 'No', note: 'Captive shoe between the lock knob and the post: the knob presses the shoe, the shoe cradles the post over an area instead of a point, so the height lock holds without marring the rod.' },
    { group: 'Headband', base: 'headband_clamp', label: 'Bow clamp plate', qty: '×2', material: 'PETG',
      orient: 'Flat', supports: 'No', note: 'Inner cover plate that sandwiches the metal bow end against the slider.' },
    { group: 'Headband', base: 'headband_pad', label: 'Headband pad', qty: '×1', material: 'Foam or printed TPU',
      orient: 'Arch on its side', supports: 'Light', note: 'Crown cushion; the channel grips the bow. Still a rough draft — form and retention are open.' },
    { group: 'Headband', base: 'bow', label: 'Head bow', qty: '×1', bought: true, material: 'Sprung steel bow — Beyerdynamic metal head bow (~$11)',
      orient: '—', supports: '—', note: 'NOT printed, and deliberately so. No FDM plastic is a good spring: a printed headband works on day one and is loose by month three. Forming our own was tried with printed jigs and failed — the steel springs back and the jig deflects first. Note we are knowingly inheriting a circumaural’s arc until a bow is stocked to our own spec.' },
    // --- Earpads ---
    { group: 'Earpads', base: 'earpad', label: 'Earpads (Grado pattern)', qty: '1 pair', bought: true, material: 'Commodity Grado-pattern foam — genuine or aftermarket',
      orient: '—', supports: '—', note: 'NOT printed and NOT in this repo. The foam stretches over the Ø54 lip and grips the Ø48 body behind it; it rotates freely but will not slide off. Swapping flats for bowls is the main bass-and-treble lever you have, and it costs about ten dollars instead of a reprint.' },
    // --- Optional ---
    { group: 'Optional', base: 'grille_dot', label: 'Logo accent cap', qty: 'optional', material: 'Accent filament',
      orient: 'Any', supports: 'No', note: 'Press-in cap at the grille centre. The logo is flush single-colour by default — add this only if you want the contrasting accent.' },
    { group: 'Optional', base: 'adapter_ring', label: 'Driver adapter ring', qty: 'optional', material: 'PETG',
      orient: 'Flat', supports: 'No', note: 'Step-down ring to host a smaller driver in a bigger baffle. NOT acoustically neutral — it changes the front cavity.' },
    { group: 'Optional', base: 'vent_plug', label: 'Tuning port plug', qty: 'optional', material: 'PETG',
      orient: 'Flange down', supports: 'No', note: 'For the closed-back variant only: press-fit plugs so openness is a reversible knob — plug N of 6 and measure. The closed-back variant does not currently fit at 54 mm (the ports and the damping ring are competing for the same floor), so treat this as parked.' },
  ],
};
